{% extends "response/base.yml" %}
{% block title_link %}
    title_link: "{{ url_way_view }}"
{% endblock %}
{% block fields %}
    fields:
      - title: "View Way"
        value: "<{{ url_way_view }}|View>"
        short: true
      - title: "View Changeset"
        value: "<{{ url_changeset_view }}|View>"
        short: true
      - title: "View User"
        value: "<{{ url_user_view }}|View>"
        short: true
{% endblock %}
